//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.13 at 11:41:10 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gaja.com/country/stubs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gaja.country.stubs;
