FROM openjdk:11.0.7-jre-slim

WORKDIR /app
COPY ./target/Spring_Soap_WS_Wss4j_Encryption_Sign-0.0.1-SNAPSHOT.jar /app

EXPOSE 8083

CMD ["java", "-jar", "./Spring_Soap_WS_Wss4j_Encryption_Sign-0.0.1-SNAPSHOT.jar"]
